name: linters
on: [ push ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ğŸ
        uses: actions/checkout@v3
      - name: install linters ğŸ˜Œ
        run: pip install black isort Flake8-pyproject
      - name: Black
        run: cd app && black . --check
      - name: Isort
        run: cd app && isort . --check-only
      - name: flake8
        run: cd app && flake8
